"""Manual source expansions kept out of the giant CURATED list.

Imported by resolve_sources. Same dict shape. New shows still go through
feeds.fetch + transcript.acquire (feed/notes/page/youtube/asr).
"""

EXTRA: list[dict] = [
  # --- ideas ---
  dict(id="tyler", name="Conversations with Tyler", zh="Conversations with Tyler",
       cat="ideas", tier=2, lang="en", itunes=983795625,
       feed="https://rss.libsyn.com/shows/137081/destinations/850607.xml",
       yt="UC_AnpBvnhXTcipgGEHLWoOg",
       desc="Tyler Cowen 逼受访者给出可反驳判断，覆盖经济、历史与思想"),
  dict(id="econtalk", name="EconTalk", zh="EconTalk", cat="ideas", tier=2, lang="en",
       itunes=135066958, feed="https://feeds.simplecast.com/wgl4xEgL",
       desc="Russ Roberts 与学者的长谈，机制与判断可回论文核对"),
  dict(id="hiddenbrain", name="Hidden Brain", zh="Hidden Brain", cat="ideas", tier=2, lang="en",
       itunes=1028908750, feed="https://feeds.npr.org/510308/podcast.xml",
       desc="Shankar Vedantam 用行为科学解释日常判断，论断可回实验与论文"),
  dict(id="inourtime", name="In Our Time", zh="In Our Time", cat="ideas", tier=2, lang="en",
       itunes=73330895, feed="https://podcasts.files.bbci.co.uk/b006qykl.rss",
       desc="Melvyn Bragg 与学者讨论思想史与科学史，可被史学界透项抬杠"),
  dict(id="philosophize", name="Philosophize This!", zh="Philosophize This!", cat="ideas", tier=2, lang="en",
       itunes=659155419, feed="https://feeds.megaphone.fm/QCD6036500916",
       desc="Stephen West 逐家讲哲学史，概念链清楚、可回原典"),
  dict(id="knowledge", name="The Knowledge Project", zh="The Knowledge Project", cat="ideas", tier=2, lang="en",
       itunes=990149481, feed="https://theknowledgeproject.libsyn.com/rss",
       desc="Shane Parrish 追决策与心智模型，受访者给出可复制的判断"),
  dict(id="freakonomics", name="Freakonomics Radio", zh="Freakonomics Radio", cat="ideas", tier=2, lang="en",
       itunes=201671138, feed="https://feeds.simplecast.com/Y8lFbOT4",
       desc="Dubner 用经济思维拆日常现象，数字与对照可核对"),
  dict(id="radiolab", name="Radiolab", zh="Radiolab", cat="ideas", tier=2, lang="en",
       itunes=152249110, feed="https://feeds.simplecast.com/EmVW7VGp",
       desc="科学与人文交叉叙事，实验与一手素材密"),
  dict(id="ninepi", name="99% Invisible", zh="99% Invisible", cat="ideas", tier=2, lang="en",
       itunes=329472913, feed="https://feeds.simplecast.com/BqbsxVfO",
       desc="设计与建筑的隐藏史，对象与档案可核对"),
  dict(id="samharris", name="Making Sense with Sam Harris", zh="Making Sense", cat="ideas", tier=3, lang="en",
       itunes=733163012, feed="https://wakingup.libsyn.com/rss",
       desc="认知科学与伦理长谈，论断可被反方抬杠"),
  dict(id="invisibilia", name="Invisibilia", zh="Invisibilia", cat="ideas", tier=3, lang="en",
       itunes=953290300, feed="https://feeds.npr.org/510307/podcast.xml",
       desc="NPR 探人性与行为中的隐形力量，故事背后有实验"),
  # --- hist ---
  dict(id="restishistory", name="The Rest Is History", zh="The Rest Is History",
       cat="hist", tier=2, lang="en", itunes=1537788786,
       feed="https://feeds.megaphone.fm/GLT4787413333",
       yt="UCwayCyXbToTPxYJUBcEx74g",
       desc="Holland 与 Sandbrook 系列化深挖历史事件，叙事密、可被史学界抬杠"),
  dict(id="fallciv", name="Fall of Civilizations", zh="Fall of Civilizations",
       cat="hist", tier=2, lang="en", itunes=1449884495,
       feed="https://anchor.fm/s/101adcf44/podcast/rss",
       desc="单文明长篇考古与一手文献，时间线与证据密度极高"),
  dict(id="throughline", name="Throughline", zh="Throughline", cat="hist", tier=2, lang="en",
       itunes=1451872743, feed="https://feeds.npr.org/510333/podcast.xml",
       desc="NPR 把当下事件推回历史线索，一手素材与时间线可核对"),
  dict(id="empire", name="Empire", zh="Empire", cat="hist", tier=2, lang="en",
       itunes=1639562281, feed="https://feeds.megaphone.fm/empire",
       desc="Dalrymple 与 Anand 讲帝国与东方史，一手档案密、可被专业史家抬杠"),
  dict(id="historyextra", name="History Extra", zh="History Extra", cat="hist", tier=2, lang="en",
       itunes=256580326, feed="https://feeds.feedburner.com/historyextra",
       desc="BBC History 学者访谈，论断给出处与反方观点"),
  dict(id="hardcore", name="Hardcore History", zh="Hardcore History", cat="hist", tier=3, lang="en",
       itunes=201671138, feed="https://feeds.feedburner.com/dancarlin/history?format=xml",
       desc="Dan Carlin 长篇战争史，叙事密度极高（更新不规律，T3）"),
  # --- parent ---
  dict(id="goodinside", name="Good Inside with Dr. Becky", zh="Good Inside",
       cat="parent", tier=2, lang="en", itunes=1561689671,
       feed="https://feeds.simplecast.com/Y5N0xWWZ",
       desc="临床心理育儿框架，论断可在真实家庭场景检验"),
  dict(id="raisinggh", name="Raising Good Humans", zh="Raising Good Humans",
       cat="parent", tier=2, lang="en", itunes=1473072044,
       feed="https://rss.art19.com/raising-good-humans",
       desc="Aliza Pressman 发展心理育儿，原则可回发展科学核对"),
  dict(id="longestshort", name="The Longest Shortest Time", zh="The Longest Shortest Time",
       cat="parent", tier=3, lang="en", itunes=901154152,
       feed="https://feeds.megaphone.fm/QCD4231325211",
       desc="育儿真实困境与专家对话，场景具体可检验"),
  # --- biz / finance / startup ---
  dict(id="colinsamir", name="The Colin and Samir Show", zh="Colin and Samir",
       cat="biz", tier=3, lang="en", itunes=1379942034,
       feed="https://feeds.megaphone.fm/LI6529969937",
       yt="UCamLstJyCa-t5gfZegxsFMw",
       desc="创作者经济机制：CPM、分成、制作成本与平台规则"),
  dict(id="planetmoney", name="Planet Money", zh="Planet Money", cat="biz", tier=2, lang="en",
       itunes=290783428, feed="https://feeds.npr.org/510289/podcast.xml",
       desc="NPR 用故事讲清经济机制，数字与对照可核对"),
  dict(id="indicator", name="The Indicator from Planet Money", zh="The Indicator", cat="biz", tier=2, lang="en",
       itunes=1321407489, feed="https://feeds.npr.org/510325/podcast.xml",
       desc="每日经济指标解读，短平快、数字可回源"),
  dict(id="howibuilt", name="How I Built This", zh="How I Built This", cat="biz", tier=2, lang="en",
       itunes=1150510297, feed="https://rss.art19.com/how-i-built-this",
       desc="Guy Raz 追创业者决策路径，关键拙折可被对方核对"),
  dict(id="masterscale", name="Masters of Scale", zh="Masters of Scale", cat="biz", tier=2, lang="en",
       itunes=1222114405, feed="https://rss.art19.com/masters-of-scale",
       desc="Reid Hoffman 与创始人讲规模化机制，可复制的增长判断"),
  dict(id="moreorless", name="More or Less", zh="More or Less", cat="biz", tier=2, lang="en",
       itunes=266351289, feed="https://podcasts.files.bbci.co.uk/b006qshd.rss",
       desc="BBC 核对新闻里的数字，给出处与误差范围"),
  dict(id="pivot", name="Pivot", zh="Pivot", cat="biz", tier=3, lang="en",
       itunes=1073221579, feed="https://feeds.megaphone.fm/pivot",
       desc="Kara Swisher 与 Scott Galloway 讲科技与商业判断，观点尖锐可抬杠"),

  # --- hist (high priority batch) ---
  dict(id="youdead", name="You're Dead to Me", zh="You're Dead to Me",
       cat="hist", tier=2, lang="en", itunes=1479973402,
       feed="https://podcasts.files.bbci.co.uk/p07mdbhg.rss",
       desc="Greg Jenner 与史家+喜剧人讲历史，事实可核、叙事密"),
  dict(id="tides", name="Tides of History", zh="Tides of History",
       cat="hist", tier=2, lang="en", itunes=1257202425,
       feed="https://rss.art19.com/tides-of-history",
       desc="Patrick Wyman 长时段历史结构，时间线与机制可核对"),
  dict(id="revolutions", name="Revolutions", zh="Revolutions",
       cat="hist", tier=2, lang="en", itunes=703889772,
       feed="https://rss.libsyn.com/shows/47475/destinations/159998.xml",
       desc="Mike Duncan 系列化革命史，一手文献密度高"),
  dict(id="witness", name="Witness History", zh="Witness History",
       cat="hist", tier=2, lang="en", itunes=339986758,
       feed="https://podcasts.files.bbci.co.uk/p004t1hd.rss",
       desc="BBC 历史亲历者口述，一手证词可被史学交叉验证"),
  dict(id="historyhit", name="Dan Snow's History Hit", zh="History Hit",
       cat="hist", tier=2, lang="en", itunes=1042631089,
       feed="https://access.acast.com/rss/c939f8d1-c4bc-478e-8bb9-e5343f9a7ab5",
       desc="Dan Snow 与史家访谈，论断给出处"),
  dict(id="ancients", name="The Ancients", zh="The Ancients",
       cat="hist", tier=2, lang="en", itunes=1520403988,
       feed="https://access.acast.com/rss/f2925f7a-eb08-471a-9958-387cb5ee6353",
       desc="古代史专题，考古与文献证据密"),
  # --- parent (high priority) ---
  dict(id="unruffled", name="Respectful Parenting: Janet Lansbury Unruffled", zh="Unruffled",
       cat="parent", tier=2, lang="en", itunes=1030050704,
       feed="https://feeds.megaphone.fm/ADL8169230773",
       desc="尊重式育儿框架，具体场景可在家庭中检验"),
  dict(id="parentmojo", name="Your Parenting Mojo", zh="Your Parenting Mojo",
       cat="parent", tier=2, lang="en", itunes=1148570190,
       feed="https://feeds.captivate.fm/yourparentingmojo/",
       desc="研究取向育儿，论断回发展科学与论文"),
  # --- ideas (high priority) ---
  dict(id="ezra", name="The Ezra Klein Show", zh="Ezra Klein Show",
       cat="ideas", tier=2, lang="en", itunes=1548604447,
       feed="https://feeds.simplecast.com/kEKXbjuJ",
       desc="长谈政策与思想，受访者判断可被反方抬杠"),
  dict(id="grayarea", name="The Gray Area with Sean Illing", zh="The Gray Area",
       cat="ideas", tier=2, lang="en", itunes=1081584611,
       feed="https://feeds.megaphone.fm/theezrakleinshow",
       desc="Vox 思想长谈，论点链条清楚"),
  dict(id="cautionary", name="Cautionary Tales with Tim Harford", zh="Cautionary Tales",
       cat="ideas", tier=2, lang="en", itunes=1484511465,
       feed="https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/c0ae8c6e-22f0-4e9b-ac1c-ae390037ac53/7f5a4714-6b10-4ccf-a424-ae390037ac70/podcast.rss",
       desc="Tim Harford 用真实失败讲决策与偏差，机制可核对"),
  dict(id="hopwag", name="History of Philosophy Without Any Gaps", zh="History of Philosophy Without Any Gaps",
       cat="ideas", tier=2, lang="en", itunes=396903391,
       feed="https://feed.podbean.com/hopwag/feed.xml",
       desc="哲学史无断档系列，概念可回原典"),


  # --- cn (high quality) ---
  dict(id="zhangjing", name="42章经", zh="42章经",
       cat="cn", tier=2, lang="zh",
       feed="https://feed.xyzfm.space/evgg6xle9rdc",
       desc="曲凯主持的创投与AI一线访谈，嘉宾密、判断可被抬杠"),
  dict(id="fengtouquan", name="疯投圈", zh="疯投圈",
       cat="cn", tier=2, lang="zh",
       feed="https://crazy.capital/feed",
       desc="独立站商业与投资拆解，机制与案例密度高"),
  dict(id="touzishizhan", name="投资实战派", zh="投资实战派",
       cat="cn", tier=2, lang="zh",
       feed="https://feed.xyzfm.space/rgnq4rbx9tpv",
       desc="公司研究取向的投资访谈，论断可回财报与行业数据"),


  # --- parent expansion ---
  dict(id="secureattach", name="Securely Attached", zh="Securely Attached",
       cat="parent", tier=2, lang="en", itunes=1570870737,
       feed="https://rss.libsyn.com/shows/351044/destinations/2868554.xml",
       desc="依恋理论育儿，临床框架可在真实亲子关系中检验"),
  dict(id="asklisa", name="Ask Lisa: The Psychology of Raising Tweens & Teens", zh="Ask Lisa",
       cat="parent", tier=2, lang="en", itunes=1525689066,
       feed="https://feeds.megaphone.fm/ADL9419958163",
       desc="青少年心理育儿问答，原则可回发展心理学"),
  dict(id="carefeed", name="Care and Feeding", zh="Care and Feeding",
       cat="parent", tier=3, lang="en", itunes=774383607,
       feed="https://my.slate.com/podcasts/feeds/care-and-feeding/",
       desc="Slate 育儿问答，场景具体、观点可被反方抬杠"),
  dict(id="sciparent", name="The Science of Parenting", zh="Science of Parenting",
       cat="parent", tier=2, lang="en", itunes=423619021,
       feed="https://rss.buzzsprout.com/748652.rss",
       desc="循证育儿，论断回研究证据"),
  # --- hist expansion ---
  dict(id="stuffmissed", name="Stuff You Missed in History Class", zh="Stuff You Missed in History Class",
       cat="hist", tier=2, lang="en", itunes=283605519,
       feed="https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/cfb428ef-eafc-44d0-9d09-ae2701747e6f/fb626e1f-112c-4246-a40d-ae2701747e7d/podcast.rss",
       desc="被忽略的历史人物与事件，时间线与一手线索可核"),
  dict(id="britishhist", name="The British History Podcast", zh="British History Podcast",
       cat="hist", tier=2, lang="en", itunes=440985304,
       feed="http://feeds.feedburner.com/TheBritishHistoryPodcast",
       desc="英国史长系列，叙事密、可被专业史家抬杠"),
  # --- ideas expansion ---
  dict(id="iq2", name="Intelligence Squared", zh="Intelligence Squared",
       cat="ideas", tier=2, lang="en", itunes=708371900,
       feed="https://feeds.megaphone.fm/NSR6363847171",
       desc="公开辩论正反方，论点链条清楚、可被抬杠"),
  dict(id="phibites", name="Philosophy Bites", zh="Philosophy Bites",
       cat="ideas", tier=2, lang="en", itunes=257042117,
       feed="https://rss.libsyn.com/shows/18828/destinations/14010.xml",
       desc="短哲学访谈，概念可回原典"),
  dict(id="pel", name="The Partially Examined Life", zh="Partially Examined Life",
       cat="ideas", tier=2, lang="en", itunes=318345767,
       feed="https://rss.libsyn.com/shows/19421/destinations/16399.xml",
       desc="哲学原典精读讨论，可核对文本"),
  dict(id="mindscape", name="Sean Carroll's Mindscape", zh="Mindscape",
       cat="ideas", tier=2, lang="en", itunes=1406534739,
       feed="https://rss.libsyn.com/shows/604590/destinations/5264190.xml",
       desc="科学与哲学长谈，论断可回论文与实验"),
  dict(id="nbphilosophy", name="New Books in Philosophy", zh="New Books in Philosophy",
       cat="ideas", tier=3, lang="en", itunes=426208821,
       feed="https://feeds.megaphone.fm/LIT3426521806",
       desc="新哲学书作者访谈，论点可回原书"),
  dict(id="nostupid", name="No Stupid Questions", zh="No Stupid Questions",
       cat="ideas", tier=2, lang="en", itunes=1510056899,
       feed="https://feeds.simplecast.com/dfh_verV",
       desc="Freakonomics 衍生，行为与决策问题可回研究"),
  # --- cn expansion ---
  dict(id="zhixing", name="知行小酒馆", zh="知行小酒馆",
       cat="cn", tier=2, lang="zh", itunes=1559695855,
       feed="https://feed.xyzfm.space/j8yp8gxkmgqr",
       desc="有知有行出品，投资与生活长谈，判断可被反方抬杠"),
  dict(id="sandian", name="三点下班", zh="三点下班",
       cat="cn", tier=2, lang="zh",
       feed="https://feed.xyzfm.space/tlel9j4tg3eu",
       desc="市场与投资观察，场景具体"),
  dict(id="eastasia", name="东亚观察局", zh="东亚观察局",
       cat="cn", tier=2, lang="zh", itunes=1508293790,
       feed="https://feed.xyzfm.space/eye-on-east-asia",
       desc="东亚政治经济观察，论断可回公开信息交叉验证"),
  dict(id="beiwanglu", name="贝望录", zh="贝望录",
       cat="cn", tier=3, lang="zh", itunes=1492415440,
       feed="http://www.ximalaya.com/album/42715423.xml",
       desc="媒体与创意人访谈，一手经历密集"),
  dict(id="bannatiewk", name="半拿铁·周刊", zh="半拿铁·周刊",
       cat="cn", tier=3, lang="zh",
       feed="https://feed.xyzfm.space/vylham8uw3ay",
       desc="商业事件周评，线索可核（主系列RSS待补）"),


  # --- sci: 健康 / 科学 ---
  dict(id="sciencevs", name="Science Vs", zh="Science Vs",
       cat="sci", tier=2, lang="en",
       feed="https://feeds.megaphone.fm/sciencevs",
       desc="用证据拆谣言，给出来源与置信度，可核对"),
  dict(id="naturepod", name="Nature Podcast", zh="Nature Podcast",
       cat="sci", tier=2, lang="en",
       feed="https://rss.acast.com/nature",
       desc="Nature 期刊科研速递，论断回论文"),
  dict(id="sciencepod", name="Science Podcast", zh="Science Magazine Podcast",
       cat="sci", tier=2, lang="en",
       feed="https://feeds.feedburner.com/sciencepodcast",
       desc="Science 杂志播客，研究与政策可回原文"),
  dict(id="ologies", name="Ologies with Alie Ward", zh="Ologies",
       cat="sci", tier=2, lang="en", itunes=1278815517,
       feed="https://feeds.simplecast.com/FO6kxYGj",
       desc="各领域科学家访谈，事实密度高、可回专业文献"),
  dict(id="skeptics", name="The Skeptics' Guide to the Universe", zh="Skeptics Guide",
       cat="sci", tier=2, lang="en",
       feed="https://feed.theskepticsguide.org/feed/rss.aspx",
       desc="科学怀疑主义与伪科学拆解，主张可核"),
  dict(id="huberman", name="Huberman Lab", zh="Huberman Lab",
       cat="sci", tier=3, lang="en",
       feed="https://feeds.megaphone.fm/hubermanlab",
       desc="神经科学与行为协议；单集质量参差，T3 严闸"),
  dict(id="tpwky", name="This Podcast Will Kill You", zh="This Podcast Will Kill You",
       cat="sci", tier=2, lang="en",
       feed="https://feeds.feedburner.com/ThisPodcastWillKillYou",
       desc="疾病与流行病学故事，机制与史实可核"),


  # --- ideas expansion batch ---
  dict(id="thinkingallowed", name="Thinking Allowed", zh="Thinking Allowed",
       cat="ideas", tier=2, lang="en",
       feed="https://podcasts.files.bbci.co.uk/b006qy05.rss",
       desc="BBC 社会学与思想访谈，论断可回研究与田野"),
  dict(id="bbcanalysis", name="Analysis", zh="BBC Analysis",
       cat="ideas", tier=2, lang="en",
       feed="https://podcasts.files.bbci.co.uk/b006r4vz.rss",
       desc="BBC 深度议题分析，正反论证清楚"),
  dict(id="startweek", name="Start the Week", zh="Start the Week",
       cat="ideas", tier=2, lang="en",
       feed="https://podcasts.files.bbci.co.uk/b006r9xr.rss",
       desc="BBC 文化与思想开周谈，嘉宾判断可抬杠"),
  dict(id="verybad", name="Very Bad Wizards", zh="Very Bad Wizards",
       cat="ideas", tier=2, lang="en",
       feed="https://feeds.podcastmirror.com/very-bad-wizards",
       desc="哲学与心理学对谈，实验与思想实验可核"),
  dict(id="rationally", name="Rationally Speaking", zh="Rationally Speaking",
       cat="ideas", tier=2, lang="en",
       feed="https://feeds.feedburner.com/rationallyspeaking",
       desc="Julia Galef 理性与认知偏差，论断可回研究"),
  dict(id="dailystoic", name="The Daily Stoic", zh="Daily Stoic",
       cat="ideas", tier=3, lang="en",
       feed="https://rss.art19.com/the-daily-stoic",
       desc="斯多葛应用短集；偏实践，T3 严闸"),

]
